alertmanager:
  config:
    route:
      receiver: n8n-webhook
      group_by: ["alertname","namespace"]
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 12h
    receivers:
      - name: n8n-webhook
        webhook_configs:
          - url: https://n8n.example.com/webhook/alertmanager
            send_resolved: true
            max_alerts: 20
