apiVersion: v1
kind: Namespace
metadata:
  name: automation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-sa
  namespace: automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n8n-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","configmaps","events","namespaces","nodes"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets","statefulsets","daemonsets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","networkpolicies"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n8n-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: n8n-readonly
subjects:
  - kind: ServiceAccount
    name: n8n-sa
    namespace: automation
